### ISSUE TITLE
Not able to run program from normal users. It’s working with root access only

### ISSUE THREAD

**Issue by spk2012** [maanas-talwar/Detect-and-Download#1]

**Comment by maanas-talwar** [comment]
It would be helpful if you share the STDERR output.
Note that the account running this script should have read-write permission in the execution directory since the code involves updating the config post-run.

**Comment by spk2012** [comment]
Thanks Manas 
We shall check and revert

@ AK - please peruse the mail for resolve.

Regards

S P Karthikeyan

**Comment by spk2012** [comment]
Dear Sir 

After installing beautifulsoup4, it is working fine with the normal user. 

$ sudo pip3.8 install -v --user beautifulsoup4 

Command line and output 

otg@otg:~/Detect-and-Download/Detect-and-Download-master$ /usr/local/python38-nic/bin/python3.8 setup.py 
***** Start Execution ***** 

***** ApacheTomcat plugin imported successfully ***** 

***** PostgreSQl plugin imported successfully ***** 

***** Ubuntu_OS plugin imported successfully ***** 

***** Nodejs plugin imported successfully ***** 

***** Nginx plugin imported successfully ***** 

***** Python plugin imported successfully ***** 

***** MariaDB plugin imported successfully ***** 

***** PHP plugin imported successfully ***** 

***** ApacheHTTPServer plugin imported successfully ***** 
Downloading to disk: httpd-2.4.46.tar.gz 

***** WordPress plugin imported successfully ***** 
***** End Execution ***** 

Regards 
Kothandapani

**Comment by spk2012** [comment]
Dear Manas 

There was an error while downloading the Python new releases. 
Rest of the tools are downloading properly. 

See the following error message. 
***** Start Execution ***** 

***** ApacheTomcat plugin imported successfully ***** 

***** PostgreSQl plugin imported successfully ***** 

***** Ubuntu_OS plugin imported successfully ***** 

***** Nodejs plugin imported successfully ***** 

***** Nginx plugin imported successfully ***** 

***** Python plugin imported successfully ***** 
Traceback (most recent call last): 
File "setup.py", line 83, in <module> 
plugin_data = a.setup_call() 
File "/home/otg/Detect-and-Download/Detect-and-Download-master/plugins/Python_plugin/code.py", line 139, in setup_call 
self.update_json() 
File "/home/otg/Detect-and-Download/Detect-and-Download-master/plugins/Python_plugin/code.py", line 76, in update_json 
new_releases, released_dates = self.check_which_released() 
File "/home/otg/Detect-and-Download/Detect-and-Download-master/plugins/Python_plugin/code.py", line 65, in check_which_released 
reqd_index = all_versions.index(released_versions[i]) 
ValueError: '3.8.6' is not in list 

Regards 
Kothandapani 
NIC, OTG, Chennai.
